/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package economia;

/**
 *
 * @author giuli
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    static Home home;
    
    public Home() {
        initComponents();
        
    }
    
    public static Home getHome()
    {
        if(home == null)
            home= new Home();
        
        return home;
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonCliente = new javax.swing.JButton();
        buttonProgettista = new javax.swing.JButton();
        Sfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonCliente.setBackground(new java.awt.Color(248, 223, 174));
        buttonCliente.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        buttonCliente.setForeground(new java.awt.Color(204, 0, 0));
        buttonCliente.setText("Cliente");
        buttonCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClienteActionPerformed(evt);
            }
        });
        getContentPane().add(buttonCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 130, 40));

        buttonProgettista.setBackground(new java.awt.Color(248, 223, 174));
        buttonProgettista.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        buttonProgettista.setForeground(new java.awt.Color(204, 0, 0));
        buttonProgettista.setText("Venditore");
        buttonProgettista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProgettistaActionPerformed(evt);
            }
        });
        getContentPane().add(buttonProgettista, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 130, 40));

        Sfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Immagini/fundo-textura-da-aguarela_1048-2727.jpg"))); // NOI18N
        getContentPane().add(Sfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClienteActionPerformed
        ViewClienti c = new ViewClienti(this);
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonClienteActionPerformed

    private void buttonProgettistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProgettistaActionPerformed
        /*ViewProgettista p = new ViewProgettista(this);
        p.setVisible(true);
        this.setVisible(false);*/
        ViewVenditore v = new ViewVenditore();
        this.setVisible(false);
        v.setVisible(true);
    }//GEN-LAST:event_buttonProgettistaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Sfondo;
    private javax.swing.JButton buttonCliente;
    private javax.swing.JButton buttonProgettista;
    // End of variables declaration//GEN-END:variables
}
