/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package economia;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author giuli
 */
public class ViewVenditore extends javax.swing.JFrame {

    /**
     * Creates new form ViewVenditore
     */
    Connection con;
    PreparedStatement ps;
    ResultSet rs;
    
    public ViewVenditore() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboSegmenti = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSegmenti = new javax.swing.JTable();
        buttonHome = new javax.swing.JButton();
        buttonAddPC = new javax.swing.JButton();
        sfondoVenditore = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboSegmenti.setFont(new java.awt.Font("Dubai Medium", 1, 12)); // NOI18N
        comboSegmenti.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Scegli Segmento", "1", "2", "3", "4", "5" }));
        comboSegmenti.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboSegmentiItemStateChanged(evt);
            }
        });
        comboSegmenti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSegmentiActionPerformed(evt);
            }
        });
        getContentPane().add(comboSegmenti, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 140, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("SEGMENTO DI MERCATO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 280, 40));

        tableSegmenti.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        tableSegmenti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PC", "Peso", "Prezzo", "Estetica", "Pr_tecnica", "RAM", "CPU", "GPU", "Comfort", "Rumore", "Autonom", "Schermo", "Val. tot"
            }
        ));
        jScrollPane1.setViewportView(tableSegmenti);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 770, 290));

        buttonHome.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        buttonHome.setText("HOME");
        buttonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHomeActionPerformed(evt);
            }
        });
        getContentPane().add(buttonHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 40));

        buttonAddPC.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        buttonAddPC.setText("AGGIUNGI PC");
        buttonAddPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddPCActionPerformed(evt);
            }
        });
        getContentPane().add(buttonAddPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 110, 40));

        sfondoVenditore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Immagini/sfondo.jpg"))); // NOI18N
        getContentPane().add(sfondoVenditore, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboSegmentiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboSegmentiItemStateChanged
      if(!comboSegmenti.getSelectedItem().toString().equals("Scegli Segmento"))
      {  try {
            con = Database.getConnection();
            String sql = "SELECT * FROM VAL_SEGMENTI WHERE SEGMENTO=? ORDER BY VALUTAZIONE DESC";
            ps = con.prepareStatement(sql);
            if(comboSegmenti.getSelectedItem().toString().equals("1"))
            {
                ps.setString(1, "1");
            }
            if(comboSegmenti.getSelectedItem().toString().equals("2"))
            {
                ps.setString(1, "2");
            }
            if(comboSegmenti.getSelectedItem().toString().equals("3"))
            {
                ps.setString(1, "3");
            }
            if(comboSegmenti.getSelectedItem().toString().equals("4"))
            {
                ps.setString(1, "4");
            }
            if(comboSegmenti.getSelectedItem().toString().equals("5"))
            {
                ps.setString(1, "5");
            }
            rs = ps.executeQuery();
            
            tableSegmenti.setModel(datamodel());
            
            con.close();
            ps.close();
            
            
        } catch (SQLException ex) {
            Logger.getLogger(ViewVenditore.class.getName()).log(Level.SEVERE, null, ex);
        }         
      }     
    }//GEN-LAST:event_comboSegmentiItemStateChanged

    private void buttonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHomeActionPerformed
        Home x = Home.getHome();
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonHomeActionPerformed

    private void comboSegmentiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSegmentiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboSegmentiActionPerformed

    private void buttonAddPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddPCActionPerformed
        this.dispose();
        AddPC pc = new AddPC();
        pc.setVisible(true);
    }//GEN-LAST:event_buttonAddPCActionPerformed

    public DefaultTableModel datamodel() throws SQLException
    {
        DefaultTableModel data = new DefaultTableModel(new Object [][] {

            },
            new String [] {
                "PC", "Peso", "Prezzo", "Estetica", "Pr_tecnica", "RAM", "CPU", "GPU", "Comfort", "Rumore", "Autonom", "Schermo", "Val. tot"
            }){

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        while(rs.next())
        {
            String x = new String(rs.getString(2));
            
            data.addRow(new Object[]{rs.getString(2),rs.getFloat(3),rs.getFloat(4),rs.getFloat(5),rs.getFloat(6),rs.getFloat(7),rs.getFloat(8),rs.getFloat(9),rs.getFloat(10),rs.getFloat(11),rs.getFloat(12),rs.getFloat(13),rs.getFloat(14)});
        }
        
        return data;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddPC;
    private javax.swing.JButton buttonHome;
    private javax.swing.JComboBox<String> comboSegmenti;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel sfondoVenditore;
    private javax.swing.JTable tableSegmenti;
    // End of variables declaration//GEN-END:variables
}
