/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package economia;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author MarcelloQuattromani
 */
public class viewValutazione extends javax.swing.JFrame
{

    /**
     * Creates new form viewValutazione
     */
    public viewValutazione()
    {
        initComponents();
    }

    public JButton getButtonBackHome()
    {
        return ButtonBackHome;
    }

    public void setButtonBackHome(JButton ButtonBackHome)
    {
        this.ButtonBackHome = ButtonBackHome;
    }

    public JLabel getImgPC1()
    {
        return ImgPC1;
    }

    public void setImgPC1(JLabel ImgPC1)
    {
        this.ImgPC1 = ImgPC1;
    }

    public JLabel getImgPC2()
    {
        return ImgPC2;
    }

    public void setImgPC2(JLabel ImgPC2)
    {
        this.ImgPC2 = ImgPC2;
    }

    public JTextField getTextValutazionePC1()
    {
        return TextValutazionePC1;
    }

    public void setTextValutazionePC1(JTextField TextValutazionePC1)
    {
        this.TextValutazionePC1 = TextValutazionePC1;
    }

    public JTextField getTextValutazionePC2()
    {
        return TextValutazionePC2;
    }

    public void setTextValutazionePC2(JTextField TextValutazionePC2)
    {
        this.TextValutazionePC2 = TextValutazionePC2;
    }

    public JTextArea getFieldPC1()
    {
        return fieldPC1;
    }

    public void setFieldPC1(JTextArea fieldPC1)
    {
        this.fieldPC1 = fieldPC1;
    }

    public JTextArea getFieldPC2()
    {
        return fieldPC2;
    }

    public void setFieldPC2(JTextArea fieldPC2)
    {
        this.fieldPC2 = fieldPC2;
    }

    public JScrollPane getjScrollPane1()
    {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1)
    {
        this.jScrollPane1 = jScrollPane1;
    }

    public JScrollPane getjScrollPane3()
    {
        return jScrollPane3;
    }

    public void setjScrollPane3(JScrollPane jScrollPane3)
    {
        this.jScrollPane3 = jScrollPane3;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        fieldPC1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        fieldPC2 = new javax.swing.JTextArea();
        TextValutazionePC1 = new javax.swing.JTextField();
        TextValutazionePC2 = new javax.swing.JTextField();
        ImgPC1 = new javax.swing.JLabel();
        ImgPC2 = new javax.swing.JLabel();
        ButtonBackHome = new javax.swing.JButton();
        Sfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fieldPC1.setColumns(20);
        fieldPC1.setRows(5);
        jScrollPane1.setViewportView(fieldPC1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 280, 220));

        fieldPC2.setColumns(20);
        fieldPC2.setRows(5);
        jScrollPane3.setViewportView(fieldPC2);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 280, 220));

        TextValutazionePC1.setText("Valutazione");
        TextValutazionePC1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                TextValutazionePC1ActionPerformed(evt);
            }
        });
        getContentPane().add(TextValutazionePC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, 270, -1));

        TextValutazionePC2.setText("Valutazione");
        TextValutazionePC2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                TextValutazionePC2ActionPerformed(evt);
            }
        });
        getContentPane().add(TextValutazionePC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 270, -1));
        getContentPane().add(ImgPC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 230, 180));
        getContentPane().add(ImgPC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 230, 180));

        ButtonBackHome.setBackground(new java.awt.Color(248, 223, 174));
        ButtonBackHome.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        ButtonBackHome.setText("Torna alla Home");
        getContentPane().add(ButtonBackHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 550, 150, 50));

        Sfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Immagini/fundo-textura-da-aguarela_1048-2727.jpg"))); // NOI18N
        getContentPane().add(Sfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextValutazionePC1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_TextValutazionePC1ActionPerformed
    {//GEN-HEADEREND:event_TextValutazionePC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextValutazionePC1ActionPerformed

    private void TextValutazionePC2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_TextValutazionePC2ActionPerformed
    {//GEN-HEADEREND:event_TextValutazionePC2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextValutazionePC2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(viewValutazione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(viewValutazione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(viewValutazione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(viewValutazione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new viewValutazione().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBackHome;
    private javax.swing.JLabel ImgPC1;
    private javax.swing.JLabel ImgPC2;
    private javax.swing.JLabel Sfondo;
    private javax.swing.JTextField TextValutazionePC1;
    private javax.swing.JTextField TextValutazionePC2;
    private javax.swing.JTextArea fieldPC1;
    private javax.swing.JTextArea fieldPC2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
