/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package economia;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author giuli
 */
public class ViewClienti extends javax.swing.JFrame {

    Home home;
    
    public ViewClienti(Home home) {
        this.home = home;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buttonBackC = new javax.swing.JButton();
        comboPrezzo = new javax.swing.JComboBox<>();
        comboPrestTecn = new javax.swing.JComboBox<>();
        comboEstetica = new javax.swing.JComboBox<>();
        comboComfort = new javax.swing.JComboBox<>();
        comboPeso = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        buttonOkC = new javax.swing.JButton();
        textObject = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Sfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonBackC.setBackground(new java.awt.Color(248, 223, 174));
        buttonBackC.setFont(new java.awt.Font("Dubai Medium", 1, 12)); // NOI18N
        buttonBackC.setText("Back");
        buttonBackC.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonBackCActionPerformed(evt);
            }
        });
        getContentPane().add(buttonBackC, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 80, 30));

        comboPrezzo.setBackground(new java.awt.Color(248, 223, 174));
        comboPrezzo.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        comboPrezzo.setForeground(new java.awt.Color(51, 51, 51));
        comboPrezzo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Scegli...", "Molto importante", "Importante", "Sufficiente", "Poco Importante", "Non importante" }));
        getContentPane().add(comboPrezzo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 140, 30));

        comboPrestTecn.setBackground(new java.awt.Color(248, 223, 174));
        comboPrestTecn.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        comboPrestTecn.setForeground(new java.awt.Color(51, 51, 51));
        comboPrestTecn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Scegli...", "Molto importante", "Importante", "Sufficiente", "Poco Importante", "Non importante" }));
        getContentPane().add(comboPrestTecn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 140, 30));

        comboEstetica.setBackground(new java.awt.Color(248, 223, 174));
        comboEstetica.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        comboEstetica.setForeground(new java.awt.Color(51, 51, 51));
        comboEstetica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Scegli...", "Molto importante", "Importante", "Sufficiente", "Poco Importante", "Non importante" }));
        getContentPane().add(comboEstetica, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 140, 30));

        comboComfort.setBackground(new java.awt.Color(248, 223, 174));
        comboComfort.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        comboComfort.setForeground(new java.awt.Color(51, 51, 51));
        comboComfort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Scegli...", "Molto importante", "Importante", "Sufficiente", "Poco Importante", "Non importante" }));
        getContentPane().add(comboComfort, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 140, 30));

        comboPeso.setBackground(new java.awt.Color(248, 223, 174));
        comboPeso.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        comboPeso.setForeground(new java.awt.Color(51, 51, 51));
        comboPeso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Scegli...", "Molto importante", "Importante", "Sufficiente", "Poco Importante", "Non importante" }));
        getContentPane().add(comboPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 140, 30));

        jLabel1.setFont(new java.awt.Font("Dubai Medium", 1, 12)); // NOI18N
        jLabel1.setText("Prezzo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 130, 30));

        jLabel2.setFont(new java.awt.Font("Dubai Medium", 1, 12)); // NOI18N
        jLabel2.setText("Prestazione Tecnica");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 130, 30));

        jLabel3.setFont(new java.awt.Font("Dubai Medium", 1, 12)); // NOI18N
        jLabel3.setText("Estetica");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 130, 30));

        jLabel4.setFont(new java.awt.Font("Dubai Medium", 1, 12)); // NOI18N
        jLabel4.setText("Comfort");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 130, 30));

        jLabel5.setFont(new java.awt.Font("Dubai Medium", 1, 12)); // NOI18N
        jLabel5.setText("Peso");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 130, 30));

        jLabel6.setFont(new java.awt.Font("Dubai Medium", 3, 14)); // NOI18N
        jLabel6.setText("IMPOSTA LE TUE PREFERENZE");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 220, -1));

        buttonOkC.setBackground(new java.awt.Color(248, 223, 174));
        buttonOkC.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        buttonOkC.setText("OK!");
        buttonOkC.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonOkCActionPerformed(evt);
            }
        });
        getContentPane().add(buttonOkC, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 70, 50));

        textObject.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        textObject.setForeground(new java.awt.Color(153, 153, 153));
        textObject.setText("Nome oggetto");
        textObject.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                textObjectFocusLost(evt);
            }
        });
        textObject.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                textObjectMouseClicked(evt);
            }
        });
        getContentPane().add(textObject, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 170, 30));

        jLabel7.setFont(new java.awt.Font("Dubai Medium", 1, 12)); // NOI18N
        jLabel7.setText("Oggetto da valutare");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 130, 30));

        Sfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Immagini/fundo-textura-da-aguarela_1048-2727.jpg"))); // NOI18N
        getContentPane().add(Sfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBackCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackCActionPerformed
        this.setVisible(false);
        home.setVisible(true);
    }//GEN-LAST:event_buttonBackCActionPerformed

    private void buttonOkCActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonOkCActionPerformed
    {//GEN-HEADEREND:event_buttonOkCActionPerformed
        if(textObject.getText().equals("Nome oggetto") || textObject.getText().equals("") || comboComfort.getSelectedItem().toString().equals("Scegli...") || comboEstetica.getSelectedItem().toString().equals("Scegli...") || comboPeso.getSelectedItem().toString().equals("Scegli...") || comboPrestTecn.getSelectedItem().toString().equals("Scegli...") || comboPrezzo.getSelectedItem().toString().equals("Scegli..."))
        {
            JOptionPane.showMessageDialog(null, "E' necessario riempire tutti i campi.", "[ATTENZIONE]", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            
        }
    }//GEN-LAST:event_buttonOkCActionPerformed

    private void textObjectMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_textObjectMouseClicked
    {//GEN-HEADEREND:event_textObjectMouseClicked
        textObject.setText(null);
        textObject.setForeground(Color.black);
    }//GEN-LAST:event_textObjectMouseClicked

    private void textObjectFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_textObjectFocusLost
    {//GEN-HEADEREND:event_textObjectFocusLost
        if(textObject.getText().equals(""))
        {
            textObject.setForeground(Color.LIGHT_GRAY);
            textObject.setText("Nome oggetto");
        }
    }//GEN-LAST:event_textObjectFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Sfondo;
    private javax.swing.JButton buttonBackC;
    private javax.swing.JButton buttonOkC;
    private javax.swing.JComboBox<String> comboComfort;
    private javax.swing.JComboBox<String> comboEstetica;
    private javax.swing.JComboBox<String> comboPeso;
    private javax.swing.JComboBox<String> comboPrestTecn;
    private javax.swing.JComboBox<String> comboPrezzo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField textObject;
    // End of variables declaration//GEN-END:variables
}
