/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package economia;

/**
 *
 * @author giuli
 */
public class ViewProgettista extends javax.swing.JFrame {

    Home home;
    
    public ViewProgettista(Home home) {
        this.home = home;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonBackP = new javax.swing.JButton();
        Sfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonBackP.setBackground(new java.awt.Color(248, 223, 174));
        buttonBackP.setText("Back");
        buttonBackP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackPActionPerformed(evt);
            }
        });
        getContentPane().add(buttonBackP, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 80, 30));

        Sfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Immagini/fundo-textura-da-aguarela_1048-2727.jpg"))); // NOI18N
        getContentPane().add(Sfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBackPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackPActionPerformed
        this.setVisible(false);
        home.setVisible(true);        
    }//GEN-LAST:event_buttonBackPActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Sfondo;
    private javax.swing.JButton buttonBackP;
    // End of variables declaration//GEN-END:variables
}
